<script lang="ts">
  import { onMount } from "svelte";
  import { Calculator, Download } from "@lucide/svelte";
  import { listExpenses, salesReport } from "../lib/tauri";
  import type { Expense, SalesReportRow } from "../lib/types";
  const today=new Date(),first=new Date(today.getFullYear(),today.getMonth(),1);
  let from=$state(first.toISOString().slice(0,10)),to=$state(today.toISOString().slice(0,10)),sales=$state<SalesReportRow[]>([]),expenses=$state<Expense[]>([]),error=$state(""),busy=$state(false);
  const cents=(rows:SalesReportRow[])=>rows.reduce((sum,row)=>sum+row.total_brl_cents,0),revenue=$derived(cents(sales)),paid=$derived(expenses.filter(e=>e.status==="Pago"&&e.due_date>=from&&e.due_date<=to).reduce((s,e)=>s+e.amount_brl_cents,0)),pending=$derived(expenses.filter(e=>e.status!=="Pago"&&e.due_date>=from&&e.due_date<=to).reduce((s,e)=>s+e.amount_brl_cents,0)),result=$derived(revenue-paid);
  const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v/100);
  async function load(){busy=true;error="";try{const begin=new Date(`${from}T00:00:00`).getTime()/1000,end=new Date(`${to}T23:59:59`).getTime()/1000;[sales,expenses]=await Promise.all([salesReport(begin,end),listExpenses()])}catch(e){error=String(e)}finally{busy=false}}
  function csv(){const text=`Indicador;Valor\nReceita de vendas;${(revenue/100).toFixed(2)}\nDespesas pagas;${(paid/100).toFixed(2)}\nResultado operacional;${(result/100).toFixed(2)}\nContas pendentes;${(pending/100).toFixed(2)}`;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/csv;charset=utf-8"}));a.download=`resultado-${from}-${to}.csv`;a.click();URL.revokeObjectURL(a.href)}
  onMount(()=>{void load()});
</script>
<section class="page-stack"><article class="card"><div class="card-header"><div><h2><Calculator size={20}/> Resultado gerencial</h2><p class="small muted">Regime de caixa baseado em vendas e despesas pagas. Não substitui escrituração do contador.</p></div><button class="button secondary" onclick={csv}><Download size={16}/> Exportar</button></div><form class="card-body filters" onsubmit={(e)=>{e.preventDefault();load()}}><label>De<input class="input" type="date" bind:value={from}/></label><label>Até<input class="input" type="date" bind:value={to}/></label><button class="button" disabled={busy}>Atualizar</button></form>{#if error}<p class="card-body error-text">{error}</p>{/if}</article><div class="summary"><article class="card card-body"><small>Receita bruta</small><strong>{brl(revenue)}</strong><span>{sales.length} vendas</span></article><article class="card card-body"><small>Despesas pagas</small><strong>{brl(paid)}</strong><span>Regime de caixa</span></article><article class="card card-body"><small>Resultado operacional</small><strong class:negative={result<0}>{brl(result)}</strong><span>Receitas menos despesas</span></article><article class="card card-body"><small>Contas pendentes</small><strong>{brl(pending)}</strong><span>Não abatidas do resultado</span></article></div><article class="card"><div class="card-header"><h2>Demonstrativo simplificado</h2></div><div class="table-wrap"><table><tbody><tr><td>(+) Receita de vendas</td><td>{brl(revenue)}</td></tr><tr><td>(−) Despesas pagas</td><td>{brl(paid)}</td></tr><tr><th>(=) Resultado operacional</th><th>{brl(result)}</th></tr></tbody></table></div></article></section>
<style>.card-header h2{display:flex;align-items:center;gap:8px}.filters{display:flex;gap:12px;align-items:end}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.summary small,.summary span{display:block;color:var(--muted);font-size:11px}.summary strong{display:block;margin:9px 0;font-size:24px}.negative{color:#b91c1c}@media(max-width:900px){.summary{grid-template-columns:1fr 1fr}}</style>
