<script lang="ts">
  import { onMount } from "svelte"; import { Banknote,CreditCard,Smartphone,LockKeyhole } from "@lucide/svelte";
  import { cashBlindClosing,cashClose,cashOpen,cashSangria,cashStatus,cashSuprimento,currentPaymentTotals,listEmployees } from "../lib/tauri"; import { brl } from "../lib/format"; import type {CashStatus,Employee,PaymentTotals} from "../lib/types";
  let status=$state<CashStatus|null>(null),employee=$state(""),counted=$state(""),cardCounted=$state(""),pixCounted=$state(""),opening=$state(""),message=$state(""),error=$state(""); let employees=$state<Employee[]>([]),paymentTotals=$state<PaymentTotals>({cash_brl_cents:0,card_brl_cents:0,pix_brl_cents:0,other_brl_cents:0}); let movementOpen=$state(false),movementType=$state<"sangria"|"suprimento">("sangria"),movementAmount=$state(""),movementDescription=$state("");
  const cents=(value:string)=>Math.round((Number(value.replace(",","."))||0)*100); let countedCents=$derived(cents(counted)),difference=$derived(countedCents-(status?.expected_brl_cents??0));
  onMount(async()=>{try{[status,employees,paymentTotals]=await Promise.all([cashStatus(),listEmployees(),currentPaymentTotals()])}catch(cause){error=cause instanceof Error?cause.message:String(cause)}}); async function openCash(){try{status=await cashOpen(cents(opening));message="Caixa aberto com sucesso."}catch(cause){error=String(cause)}}
  async function saveMovement(){if(!status?.session_id)return;try{if(movementType==="sangria")await cashSangria(status.session_id,cents(movementAmount),movementDescription,employee);else await cashSuprimento(status.session_id,cents(movementAmount),movementDescription,employee);status=await cashStatus();movementOpen=false;movementAmount=movementDescription="";message=movementType==="sangria"?"Sangria registrada.":"Suprimento registrado."}catch(cause){error=String(cause)}}
  async function close(){if(!status?.session_id||!employee)return;try{const report=await cashBlindClosing(status.session_id,countedCents,cents(cardCounted),cents(pixCounted));status=await cashClose(countedCents);message=`Caixa fechado. Diferença total conferida: ${brl(report.difference)}`}catch(cause){error=String(cause)}}
</script>
{#if error}<div class="card card-body"><span class="badge danger">{error}</span></div>{/if}
{#if status && !status.open}<article class="card open-card"><div class="card-header"><div><h2>Abertura de Caixa</h2><p class="small muted">Informe o fundo inicial para começar o turno.</p></div><span class="stat-icon"><LockKeyhole size={19}/></span></div><div class="card-body section-stack"><label>Fundo inicial<input class="input" type="number" min="0" step="0.01" bind:value={opening}/></label>{#if message}<p class="result">{message}</p>{/if}<button class="button" onclick={openCash}>Abrir caixa</button></div></article>
{:else if status}<div class="closing-grid"><article class="card"><div class="card-header"><div><h2>Fechamento de Caixa</h2><p class="small muted">Conferência cega de todos os meios de pagamento.</p></div><span class="stat-icon"><LockKeyhole size={19}/></span></div><div class="card-body section-stack"><label>Funcionário<select bind:value={employee}><option value="">Selecione</option>{#each employees.filter(item=>item.status==="Ativo") as item}<option value={item.id}>{item.name}</option>{/each}</select></label><div class="summary"><h3>Resumo registrado</h3><div><span><Banknote size={17}/> Dinheiro</span><strong>{brl(paymentTotals.cash_brl_cents)}</strong></div><div><span><CreditCard size={17}/> Cartão</span><strong>{brl(paymentTotals.card_brl_cents)}</strong></div><div><span><Smartphone size={17}/> PIX</span><strong>{brl(paymentTotals.pix_brl_cents)}</strong></div></div>{#if message}<p class="result">{message}</p>{/if}</div></article><article class="card side"><div class="card-header"><h2>Valores contados</h2></div><div class="card-body section-stack"><div class="row"><span>Dinheiro esperado</span><strong>{brl(status.expected_brl_cents)}</strong></div><label>Dinheiro<input class="input" type="number" step="0.01" bind:value={counted}/></label><label>Cartão<input class="input" type="number" step="0.01" bind:value={cardCounted}/></label><label>PIX<input class="input" type="number" step="0.01" bind:value={pixCounted}/></label><div class:negative={difference<0} class:positive={difference>0} class="difference"><span>Diferença do dinheiro</span><strong>{brl(difference)}</strong></div><div class="movement-actions"><button class="button secondary" disabled={!employee} onclick={()=>{movementType="sangria";movementOpen=true}}>Sangria</button><button class="button secondary" disabled={!employee} onclick={()=>{movementType="suprimento";movementOpen=true}}>Suprimento</button></div></div><div class="card-footer"><button class="button finish" disabled={!employee||counted===""} onclick={close}>Finalizar Fechamento Cego</button></div></article></div>
{:else}<div class="card card-body">Carregando caixa...</div>{/if}
{#if movementOpen}<div class="modal-backdrop"><form class="modal card" onsubmit={(event)=>{event.preventDefault();saveMovement()}}><div class="card-header"><h2>{movementType==="sangria"?"Registrar sangria":"Registrar suprimento"}</h2></div><div class="card-body form-grid"><label>Valor<input class="input" required min="0.01" step="0.01" type="number" bind:value={movementAmount}/></label><label class="wide">Descrição<input class="input" required bind:value={movementDescription}/></label></div><div class="card-footer modal-actions"><button type="button" class="button secondary" onclick={()=>movementOpen=false}>Cancelar</button><button class="button">Confirmar</button></div></form></div>{/if}
<style>.open-card{max-width:520px;margin:auto}.closing-grid{display:grid;grid-template-columns:1.5fr .8fr;gap:18px}.section-stack label{display:grid;gap:7px;font-size:12px;font-weight:650}.summary{display:grid;gap:2px;padding:17px;border:1px solid #e1e3ef;border-radius:10px}.summary h3{font-size:14px;margin-bottom:9px}.summary>div,.row,.difference{display:flex;justify-content:space-between;align-items:center;padding:10px 0;border-bottom:1px solid #eceef5}.summary>div:last-child{border:0}.summary span{display:flex;align-items:center;gap:8px}.side{height:max-content}.difference{padding:12px;border:0;border-radius:8px;background:#f3f4f8}.difference.negative{color:#dc3e4d;background:#feecef}.difference.positive{color:#16845b;background:#e6f7ef}.finish{width:100%}.result{padding:10px;border-radius:8px;color:#16845b;background:#e6f7ef}.movement-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}@media(max-width:800px){.closing-grid{grid-template-columns:1fr}}</style>
