<script lang="ts">
  let { onBack }: { onBack: () => void } = $props();
  let storeName=$state(""), email=$state(""), city=$state(""), modality=$state("purchase"), sent=$state(false), error=$state("");
  async function send(){error="";try{const response=await fetch("/api/v1/commercial/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({store_name:storeName,email,city,modality})});if(!response.ok)throw new Error();sent=true}catch{error="Não foi possível registrar agora. Use o e-mail abaixo."}}
</script>

<main class="contact"><header><a href="/" class="mark">_,CTRL</a><button onclick={onBack}>Voltar</button></header><article><p>CONTATO COMERCIAL</p><h1>Vamos montar uma operação que caiba na sua loja.</h1><p class="lead">Deixe seus dados. A proposta separa software, implantação e equipamento.</p>{#if sent}<div class="sent">Recebemos seu interesse. A equipe comercial entra em contato.</div>{:else}<form onsubmit={(e)=>{e.preventDefault();send()}}><input required bind:value={storeName} placeholder="Nome da loja"/><input required type="email" bind:value={email} placeholder="Seu e-mail"/><input bind:value={city} placeholder="Cidade"/><select bind:value={modality}><option value="purchase">Quero comprar equipamentos</option><option value="loan">Quero comodato</option></select><button>Registrar interesse</button></form>{#if error}<small>{error}</small>{/if}{/if}<a class="mail" href="mailto:contato@commercectrl.com.br?subject=Proposta%20CommerceCTRL">contato@commercectrl.com.br</a><div class="steps"><span>1. Entendemos sua rotina</span><span>2. Separamos plano e equipamentos</span><span>3. Marcamos a demonstração</span></div><small>Integrações, emissão fiscal e balança são confirmadas por compatibilidade e homologação antes de entrar na proposta.</small></article></main>

<style>.contact{min-height:100vh;background:#143c30;color:#f5f1e8;font-family:Inter,system-ui;padding:0 clamp(22px,9vw,150px) 70px}.contact header{height:76px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #547365}.mark{font:900 23px "Space Grotesk";letter-spacing:-.12em;color:#d9ee55;text-decoration:none}.contact button{border:0;background:transparent;color:#d9ee55;font-weight:800;cursor:pointer}.contact article{max-width:850px;margin:90px auto}.contact article>p:first-child{font-size:12px;font-weight:800;color:#d9ee55}.contact h1{font:700 clamp(48px,7vw,84px)/.92 "Space Grotesk";letter-spacing:-.08em;margin:14px 0 28px}.lead{max-width:620px;font-size:19px;line-height:1.55;color:#c8d8cc}form{max-width:560px;display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:28px 0}form input,form select{padding:14px;border:0;background:#f5f1e8;color:#143c30;font:14px Inter}form button{grid-column:1/-1!important;background:#d9ee55!important;color:#143c30!important;padding:14px!important}.sent{max-width:560px;margin:28px 0;padding:16px;background:#d9ee55;color:#143c30;font-weight:750}.mail{display:inline-block;margin:18px 0 34px;color:#143c30;background:#d9ee55;padding:16px 19px;font-weight:850;text-decoration:none}.steps{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid #547365;border-bottom:1px solid #547365}.steps span{padding:18px;border-right:1px solid #547365;font-size:13px}.steps span:last-child{border:0}.contact small{display:block;max-width:600px;margin-top:24px;line-height:1.45;color:#aac0b0}@media(max-width:600px){.contact article{margin-top:65px}form{grid-template-columns:1fr}.steps{grid-template-columns:1fr}.steps span{border-right:0;border-bottom:1px solid #547365}.steps span:last-child{border:0}}</style>
