<script lang="ts">
  import { onMount } from "svelte";
  import { Images, Volume2 } from "@lucide/svelte";
  import { getDisplaySettings, listProducts, listPromotions } from "../lib/tauri";
  import type { Product, Promotion } from "../lib/types";
  let promotions=$state<Promotion[]>([]), products=$state<Product[]>([]), index=$state(0), error=$state(""), audio=$state<HTMLAudioElement|null>(null), soundNeedsGesture=$state(false), brandName=$state("Mercadinho Martins"), brandLogo=$state("");
  let promotion=$derived(promotions[index%Math.max(1,promotions.length)]), product=$derived(products.find(p=>p.description.toLocaleLowerCase("pt-BR")===promotion?.title.toLocaleLowerCase("pt-BR")));
  const next=()=>{if(promotions.length)index=(index+1)%promotions.length};
  const image=(item:Product|undefined)=>item?(item.image_url||`http://127.0.0.1:8088/assets/demo-product/${encodeURIComponent(item.ean)}`):"";
  async function refresh(){try{const currentId=promotion?.id;[promotions,products]=await Promise.all([listPromotions(),listProducts(1000)]);const found=promotions.findIndex(i=>i.id===currentId);index=found>=0?found:0;error=""}catch(cause){error=cause instanceof Error?cause.message:"Falha ao atualizar promoções"}}
  async function setupAudio(){const settings=await getDisplaySettings();if(!settings.selected_radio_url)return;audio?.pause();audio=new Audio(settings.selected_radio_url);audio.loop=true;try{await audio.play();soundNeedsGesture=false}catch{soundNeedsGesture=true}}
  async function activateSound(){try{await audio?.play();soundNeedsGesture=false}catch{soundNeedsGesture=true}}
  onMount(()=>{try{const saved=JSON.parse(localStorage.getItem("commercectrl.client.branding")??"null");brandName=saved?.name||brandName;brandLogo=saved?.logo||""}catch{}const changed=(event:Event)=>{const value=(event as CustomEvent<{name:string;logo:string}>).detail;brandName=value.name||brandName;brandLogo=value.logo||""};window.addEventListener("commercectrl-branding",changed);void refresh();void setupAudio().catch(()=>{});let rotation=10_000;getDisplaySettings().then(s=>rotation=Math.max(5,s.promotion_interval_seconds)*1000).catch(()=>{});const refreshTimer=window.setInterval(()=>void refresh(),5_000);const rotationTimer=window.setInterval(()=>next(),rotation);return()=>{audio?.pause();window.clearInterval(refreshTimer);window.clearInterval(rotationTimer);window.removeEventListener("commercectrl-branding",changed)}});
</script>
<svelte:window onkeydown={(event)=>{if(event.key==="ArrowRight")next()}}/>
<main class="display-screen"><header><div class="display-brand">{#if brandLogo}<img src={brandLogo} alt="Logo da loja"/>{/if}<strong>{brandName}</strong></div><span>OFERTAS DA LOJA</span></header>{#if error&&!promotion}<div class="empty"><h1>Display offline</h1><p>{error}</p></div>{:else if !promotion}<div class="empty"><h1>Sem promoções ativas</h1><p>Ative uma promoção no painel da unidade.</p></div>{:else}<section class="promotion" role="button" tabindex="0" onclick={next} onkeydown={(event)=>{if(event.key==="Enter"||event.key===" ")next()}}><div class="promo-image">{#if product}<img src={image(product)} alt={product.description}/>{:else}<span>{promotion.title.slice(0,1)}</span>{/if}</div><div><p class="highlight">{promotion.subtitle??"OFERTA"}</p><h1>{promotion.title}</h1><p class="price">{promotion.price_label}</p><small>Válido enquanto durarem os estoques</small></div></section>{/if}<div class="display-actions">{#if soundNeedsGesture}<button onclick={activateSound}>Ativar som <Volume2 size={20}/></button>{/if}<button onclick={next}>Próxima <Images size={20}/></button></div></main>
<style>.display-screen{position:fixed;inset:0;overflow:hidden;padding:36px 5vw;background:#ffd928;color:#1c160b;border:18px solid #d71920}.display-screen:before{content:"OFERTA • OFERTA • OFERTA • OFERTA • OFERTA";position:absolute;inset:7px 0 auto;color:#fff;font:900 17px/1 'Space Grotesk';letter-spacing:.18em;white-space:nowrap}.display-screen header{display:flex;justify-content:space-between;align-items:center;position:relative;z-index:2;background:#d71920;color:#fff;border:5px solid #fff;padding:12px 24px;box-shadow:0 8px #9d1015;font-weight:900;letter-spacing:.1em}.display-brand{display:flex;align-items:center;gap:14px}.display-brand img{width:72px;height:54px;object-fit:contain;background:#fff;border-radius:8px;padding:3px}.display-brand strong{font-size:clamp(22px,3vw,46px);text-transform:uppercase}.promotion{position:relative;z-index:2;height:72vh;display:grid;grid-template-columns:.85fr 1.15fr;gap:5vw;align-items:center;cursor:pointer}.promo-image{aspect-ratio:1;display:grid;place-items:center;border:8px solid #d71920;border-radius:28px;background:#fff;box-shadow:13px 15px #a98512;overflow:hidden}.promo-image img{width:100%;height:100%;object-fit:contain;padding:5%}.promo-image span{color:#d71920;font:900 clamp(100px,17vw,280px) 'Space Grotesk'}.highlight{display:inline-block;padding:9px 18px;background:#fff;box-shadow:6px 6px #1c160b;font-weight:900;text-transform:uppercase}.promotion h1{margin:24px 0 8px;font-size:clamp(48px,7vw,110px);line-height:.9;text-transform:uppercase;letter-spacing:-.055em}.price{display:inline-block;padding:7px 22px;font:900 clamp(60px,8vw,135px) 'Space Grotesk';color:#fff;background:#d71920;border:5px solid #fff;margin:18px 0;transform:rotate(-2deg)}.promotion small{display:block;color:#7b1115;font-weight:900}.display-actions{position:fixed;z-index:4;right:30px;bottom:22px;display:flex;gap:8px}.display-actions button{display:flex;align-items:center;gap:8px;padding:10px 14px;border:2px solid #fff;border-radius:8px;background:#d71920;color:#fff;font-weight:800}.empty{height:75vh;display:grid;place-content:center;justify-items:center;text-align:center}.empty h1{font-size:60px}@media(max-width:800px){.promotion{grid-template-columns:1fr}.promo-image{display:none}.display-screen header>span{display:none}}</style>
