<script lang="ts">
  import { onMount } from "svelte";
  import { KeyRound, Pencil, Plus, X } from "@lucide/svelte";
  import { listEmployees, provisionEmployeeLogin, saveEmployee, setEmployeeStatus, updateEmployee } from "../lib/tauri";
  import type { Employee } from "../lib/types";
  let employees=$state<Employee[]>([]),error=$state(""),open=$state(false),accessOpen=$state(false),busy=$state(false);
  let name=$state(""),role=$state("Caixa"),status=$state("Ativo"),editingId=$state<number|null>(null),accessEmployee=$state<Employee|null>(null);
  let username=$state(""),accessRole=$state("cashier"),temporaryPassword=$state("123456");
  onMount(async()=>{try{employees=await listEmployees()}catch(cause){error=cause instanceof Error?cause.message:"Falha ao carregar funcionários"}});
  function create(){editingId=null;name="";role="Caixa";status="Ativo";open=true}
  function edit(item:Employee){editingId=item.id;name=item.name;role=item.role;status=item.status;open=true}
  function access(item:Employee){accessEmployee=item;username=item.name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,".").replace(/^\.|\.$/g,"");accessRole=item.role.toLowerCase().includes("ger")?"manager":"cashier";temporaryPassword="123456";accessOpen=true}
  async function submit(){busy=true;error="";try{const saved=editingId===null?await saveEmployee(name,role,status):await updateEmployee(editingId,name,role,status);employees=editingId===null?[saved,...employees]:employees.map(item=>item.id===saved.id?saved:item);open=false}catch(cause){error=String(cause)}finally{busy=false}}
  async function saveAccess(){if(!accessEmployee)return;busy=true;error="";try{await provisionEmployeeLogin(accessEmployee.id,username,accessRole,temporaryPassword);accessOpen=false}catch(cause){error=String(cause)}finally{busy=false}}
  async function toggle(item:Employee){const next=item.status==="Ativo"?"Inativo":"Ativo";await setEmployeeStatus(item.id,next);item.status=next;employees=[...employees]}
</script>
{#if error}<div class="card card-body"><span class="badge danger">{error}</span></div>{/if}
<article class="card"><div class="card-header"><div><h2>Gestão de Funcionários</h2><p class="small muted">Equipe e acessos individuais com permissões por cargo.</p></div><button class="button" onclick={create}><Plus size={17}/> Adicionar Funcionário</button></div><div class="table-wrap"><table><thead><tr><th>Funcionário</th><th>Cargo</th><th>Status</th><th>Ação</th></tr></thead><tbody>{#each employees as employee}<tr><td><div class="person"><span>{employee.name[0]}</span><div><strong>{employee.name}</strong><br/><small class="muted">ID {employee.id}</small></div></div></td><td><span class="badge">{employee.role}</span></td><td><span class:success={employee.status==="Ativo"} class:danger={employee.status!=="Ativo"} class="badge">{employee.status}</span></td><td><div class="actions"><button class="button secondary" onclick={()=>edit(employee)}><Pencil size={15}/> Editar</button><button class="button secondary" disabled={employee.status!=="Ativo"} onclick={()=>access(employee)}><KeyRound size={15}/> Acesso</button><button class="button secondary" onclick={()=>toggle(employee)}>{employee.status==="Ativo"?"Desativar":"Ativar"}</button></div></td></tr>{/each}</tbody></table></div></article>
{#if open}<div class="modal-backdrop"><form class="modal card" onsubmit={(e)=>{e.preventDefault();submit()}}><div class="card-header"><h2>{editingId===null?"Novo funcionário":"Editar funcionário"}</h2><button type="button" class="icon-button" onclick={()=>open=false}><X size={18}/></button></div><div class="card-body form-grid"><label class="wide">Nome<input class="input" required bind:value={name}/></label><label>Cargo<input class="input" required bind:value={role}/></label><label>Status<select bind:value={status}><option>Ativo</option><option>Inativo</option></select></label></div><div class="card-footer modal-actions"><button type="button" class="button secondary" onclick={()=>open=false}>Cancelar</button><button class="button" disabled={busy}>Salvar</button></div></form></div>{/if}
{#if accessOpen && accessEmployee}<div class="modal-backdrop"><form class="modal card" onsubmit={(e)=>{e.preventDefault();saveAccess()}}><div class="card-header"><div><h2>Acesso de {accessEmployee.name}</h2><p class="small muted">A senha deverá ser trocada no primeiro login.</p></div><button type="button" class="icon-button" onclick={()=>accessOpen=false}><X size={18}/></button></div><div class="card-body form-grid"><label class="wide">Usuário<input class="input" minlength="3" required bind:value={username}/></label><label>Perfil<select bind:value={accessRole}><option value="cashier">Caixa</option><option value="stock">Estoque</option><option value="finance">Financeiro</option><option value="viewer">Consulta</option><option value="manager">Gerente</option><option value="admin">Administrador</option></select></label><label>Senha temporária<input class="input" type="password" minlength="6" required bind:value={temporaryPassword}/></label></div><div class="card-footer modal-actions"><button type="button" class="button secondary" onclick={()=>accessOpen=false}>Cancelar</button><button class="button" disabled={busy}>Criar ou redefinir acesso</button></div></form></div>{/if}
<style>.person{display:flex;align-items:center;gap:10px}.person>span{width:36px;height:36px;display:grid;place-items:center;border-radius:50%;background:#e9ebfb;color:#4e59b5;font-weight:800}</style>
