<script lang="ts">
  import { onMount } from "svelte";
  import { Plus, Clock, CircleCheck, Pencil, X } from "@lucide/svelte";
  import { listExpenses, saveExpense, setExpenseStatus, updateExpense } from "../lib/tauri";
  import { brl } from "../lib/format";
  import type { Expense } from "../lib/types";
  let expenses = $state<Expense[]>([]); let error = $state("");
  let open=$state(false),busy=$state(false),description=$state(""),category=$state("Geral"),amount=$state(0),dueDate=$state(new Date().toISOString().slice(0,10)),status=$state("Pendente"),editingId=$state<number|null>(null);
  onMount(async()=>{try{expenses=await listExpenses()}catch(cause){error=cause instanceof Error?cause.message:"Falha ao carregar despesas"}});
  let total=$derived(expenses.reduce((sum,item)=>sum+item.amount_brl_cents,0));
  let pending=$derived(expenses.filter((item)=>item.status==="Pendente"));
  function create(){editingId=null;description="";category="Geral";amount=0;dueDate=new Date().toISOString().slice(0,10);status="Pendente";open=true}
  function edit(item:Expense){editingId=item.id;description=item.description;category=item.category;amount=item.amount_brl_cents/100;dueDate=item.due_date;status=item.status;open=true}
  async function submit(){busy=true;try{const cents=Math.round(amount*100);const saved=editingId===null?await saveExpense(description,category,cents,dueDate,status):await updateExpense(editingId,description,category,cents,dueDate,status);expenses=editingId===null?[saved,...expenses]:expenses.map((item)=>item.id===saved.id?saved:item);open=false}catch(cause){error=String(cause)}finally{busy=false}}
  async function toggle(item:Expense){const next=item.status==="Pago"?"Pendente":"Pago";await setExpenseStatus(item.id,next);item.status=next;expenses=[...expenses]}
</script>
{#if error && !expenses.length}<div class="card card-body"><span class="badge danger">{error}</span></div>{:else}<div class="section-stack"><section class="grid grid-2"><article class="card card-body"><p class="small muted">Total de despesas</p><p class="metric">{brl(total)}</p><p class="small muted">Registros locais</p></article><article class="card card-body"><p class="small muted">Despesas pendentes</p><p class="metric">{brl(pending.reduce((s,i)=>s+i.amount_brl_cents,0))}</p><p class="small muted">{pending.length} contas a vencer</p></article></section><article class="card"><div class="card-header"><div><h2>Controle de Despesas</h2><p class="small muted">Registros persistidos no SQLite.</p></div><button class="button" onclick={create}><Plus size={17}/> Adicionar Despesa</button></div><div class="table-wrap"><table><thead><tr><th>Descrição</th><th>Categoria</th><th>Valor</th><th>Vencimento</th><th>Status</th><th>Ação</th></tr></thead><tbody>{#each expenses as item}<tr><td><strong>{item.description}</strong></td><td>{item.category}</td><td>{brl(item.amount_brl_cents)}</td><td>{item.due_date}</td><td><span class:success={item.status==="Pago"} class:warning={item.status!=="Pago"} class="badge">{#if item.status==="Pago"}<CircleCheck size={13}/>{:else}<Clock size={13}/>{/if}{item.status}</span></td><td><div class="actions"><button class="button secondary" onclick={()=>edit(item)}><Pencil size={15}/> Editar</button><button class="button secondary" onclick={()=>toggle(item)}>{item.status==="Pago"?"Reabrir":"Marcar paga"}</button></div></td></tr>{/each}</tbody></table></div></article></div>{/if}
{#if open}<div class="modal-backdrop"><form class="modal card" onsubmit={(e)=>{e.preventDefault();submit()}}><div class="card-header"><h2>{editingId===null?"Nova despesa":"Editar despesa"}</h2><button type="button" class="icon-button" onclick={()=>open=false}><X size={18}/></button></div><div class="card-body form-grid"><label class="wide">Descrição<input class="input" required bind:value={description}/></label><label>Categoria<input class="input" required bind:value={category}/></label><label>Valor (R$)<input class="input" required min="0.01" step="0.01" type="number" bind:value={amount}/></label><label>Vencimento<input class="input" required type="date" bind:value={dueDate}/></label><label>Status<select bind:value={status}><option>Pendente</option><option>Pago</option></select></label></div><div class="card-footer modal-actions"><button type="button" class="button secondary" onclick={()=>open=false}>Cancelar</button><button class="button" disabled={busy}>Salvar</button></div></form></div>{/if}
