<script lang="ts">
  import { onMount } from "svelte";
  import JsBarcode from "jsbarcode";
  import { Printer, Search, Tags } from "@lucide/svelte";
  import { listProducts } from "../lib/tauri";
  import type { Product } from "../lib/types";
  let products=$state<Product[]>([]), selected=$state<Record<string,number>>({}), query=$state(""), columns=$state(3), showPrice=$state(true), error=$state("");
  const filtered=$derived(products.filter(p=>p.active&&(!query||`${p.ean} ${p.description} ${p.brand??""}`.toLowerCase().includes(query.toLowerCase()))));
  const labels=$derived(products.flatMap(product=>Array.from({length:selected[product.ean]??0},()=>product)));
  const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v/100);
  function barcode(node:SVGSVGElement,value:string){const draw=(code:string)=>JsBarcode(node,code,{format:"CODE128",displayValue:true,fontSize:13,height:42,margin:2});draw(value);return{update:draw}}
  function setCopies(ean:string,delta:number){selected[ean]=Math.max(0,Math.min(99,(selected[ean]??0)+delta));selected={...selected}}
  onMount(()=>{listProducts(1000).then(v=>products=v).catch(e=>error=e instanceof Error?e.message:"Falha ao carregar produtos")});
</script>
<section class="page-stack labels-page">
  <article class="card no-print"><div class="card-header"><div><h2><Tags size={20}/> Etiquetas de produtos</h2><p class="small muted">Selecione as quantidades e imprima em qualquer impressora instalada pelo diálogo do Windows.</p></div><button class="button" disabled={!labels.length} onclick={()=>window.print()}><Printer size={17}/> Imprimir {labels.length} etiqueta(s)</button></div>
    <div class="card-body toolbar"><div class="search"><Search size={17}/><input class="input" bind:value={query} placeholder="Produto ou código"/></div><label>Colunas<select bind:value={columns}><option value={2}>2</option><option value={3}>3</option><option value={4}>4</option></select></label><label class="check"><input type="checkbox" bind:checked={showPrice}/> Exibir preço</label></div>{#if error}<p class="card-body error-text">{error}</p>{/if}
    <div class="table-wrap"><table><thead><tr><th>Produto</th><th>EAN/código</th><th>Preço</th><th>Quantidade</th></tr></thead><tbody>{#each filtered as product}<tr><td><strong>{product.description}</strong><br/><small class="muted">{product.brand??product.part_number}</small></td><td><code>{product.ean}</code></td><td>{brl(product.price_brl_cents)}</td><td><div class="stepper"><button onclick={()=>setCopies(product.ean,-1)}>−</button><strong>{selected[product.ean]??0}</strong><button onclick={()=>setCopies(product.ean,1)}>+</button></div></td></tr>{:else}<tr><td colspan="4" class="muted">Nenhum produto encontrado.</td></tr>{/each}</tbody></table></div>
  </article>
  <article class="card print-preview"><div class="card-header no-print"><div><h2>Prévia</h2><p class="small muted">Código de barras CODE128, compatível com leitor comum.</p></div></div><div class="label-sheet" style={`--columns:${columns}`}>{#each labels as product}<div class="product-label"><strong>{product.description}</strong><small>{product.brand??"Mercadinho Martins"}</small>{#if showPrice}<b>{brl(product.price_brl_cents)}</b>{/if}<svg use:barcode={product.ean}></svg></div>{:else}<p class="empty no-print">Adicione etiquetas usando os botões acima.</p>{/each}</div></article>
</section>
<style>.card-header h2{display:flex;align-items:center;gap:8px}.toolbar{display:flex;gap:16px;align-items:end}.search{flex:1;display:flex;align-items:center;gap:8px}.stepper{display:inline-grid;grid-template-columns:34px 40px 34px;align-items:center;text-align:center}.stepper button{height:32px;border:1px solid var(--border);background:var(--surface);color:inherit}.label-sheet{display:grid;grid-template-columns:repeat(var(--columns),1fr);gap:3mm;padding:8mm;background:#fff;color:#111}.product-label{min-height:35mm;border:1px dashed #aaa;padding:3mm;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;overflow:hidden}.product-label>strong{font-size:12px;line-height:1.15}.product-label>small{font-size:9px;color:#444}.product-label>b{font-size:20px;margin:2px 0}.product-label svg{width:100%;max-height:55px}.empty{grid-column:1/-1;text-align:center;color:#666}@media print{.app-shell .sidebar,.topbar,.no-print{display:none!important}.workspace,.workspace main{margin:0!important;padding:0!important}.print-preview{border:0!important;box-shadow:none!important}.label-sheet{padding:0}.product-label{break-inside:avoid}.labels-page{display:block}}@media(max-width:700px){.toolbar{align-items:stretch;flex-direction:column}.label-sheet{grid-template-columns:1fr!important}}</style>
