<script lang="ts">
  import { LockKeyhole, Store, UserRound } from "@lucide/svelte";
  import { changeOwnPassword, loginEmployee } from "../lib/tauri";
  import type { UserSession } from "../lib/types";
  let { onLogin }:{onLogin:(session:UserSession)=>void}=$props();
  let username=$state("admin"),password=$state(""),newPassword=$state(""),confirmation=$state(""),current=$state(""),session=$state<UserSession|null>(null),firstAccess=$state(false),busy=$state(false),error=$state("");
  async function submit(){busy=true;error="";try{const result=await loginEmployee(username,password);if(result.must_change_password){session=result.session;current=password;firstAccess=true}else onLogin(result.session)}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function change(){if(newPassword!==confirmation){error="As senhas não coincidem";return}busy=true;try{await changeOwnPassword(current,newPassword);if(session)onLogin(session)}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
</script>
<main class="login-screen"><div class="shutter" aria-hidden="true"></div><section class="login-card"><header><span><Store size={32}/></span><div><small>TERMINAL DE VENDAS</small><h1>Mercadinho Martins</h1></div></header>{#if firstAccess}<form onsubmit={(e)=>{e.preventDefault();change()}}><h2>Proteja seu primeiro acesso</h2><p>Troque a senha provisória antes de usar o caixa.</p><label>Nova senha<input type="password" minlength="8" required bind:value={newPassword}/></label><label>Confirmar senha<input type="password" minlength="8" required bind:value={confirmation}/></label>{#if error}<div class="error">{error}</div>{/if}<button disabled={busy}><LockKeyhole size={19}/> Salvar e entrar</button></form>{:else}<form onsubmit={(e)=>{e.preventDefault();submit()}}><h2>Abrir terminal</h2><p>Entre com seu usuário de funcionário.</p><label>Usuário<div class="field"><UserRound size={18}/><input autocomplete="username" required bind:value={username}/></div></label><label>Senha<div class="field"><LockKeyhole size={18}/><input type="password" autocomplete="current-password" required bind:value={password}/></div></label>{#if error}<div class="error">{error}</div>{/if}<button disabled={busy}>{busy?"Validando…":"Entrar no PDV"}</button><small class="hint">Primeiro acesso: admin / 123456</small></form>{/if}</section></main>
<style>.login-screen{position:fixed;inset:0;display:grid;place-items:center;overflow:hidden;background:#121715;color:#172019;font-family:Inter,sans-serif}.shutter{position:absolute;inset:0;background:repeating-linear-gradient(180deg,#343a37 0 34px,#202522 35px 40px);opacity:.9}.shutter:after{content:"";position:absolute;inset:0;background:radial-gradient(circle at 50% 45%,transparent,#080b09 78%)}.login-card{position:relative;width:min(430px,calc(100vw - 32px));border:1px solid #d8e4dc;border-radius:24px;background:#f8fbf9;box-shadow:0 30px 90px #000c;overflow:hidden}.login-card header{display:flex;align-items:center;gap:14px;padding:22px 26px;background:#13251c;color:#fff;border-bottom:5px solid #19a765}.login-card header>span{width:54px;height:54px;display:grid;place-items:center;border-radius:15px;background:#19a765}.login-card small{letter-spacing:.15em}.login-card h1{margin:4px 0 0;font-size:21px}.login-card form{padding:27px;display:grid;gap:16px}.login-card h2{margin:0;font-size:23px}.login-card p{margin:-8px 0 4px;color:#647069}.login-card label{display:grid;gap:7px;font-size:12px;font-weight:800}.field{display:flex;align-items:center;gap:9px;padding:0 12px;border:1px solid #ccd8d0;border-radius:11px;background:#fff}.field input,.login-card label>input{height:45px;width:100%;border:0;outline:0;background:transparent}.login-card label>input{padding:0 12px;border:1px solid #ccd8d0;border-radius:11px;background:#fff}.login-card button{height:48px;border:0;border-radius:12px;background:#118653;color:#fff;font-weight:900;display:flex;justify-content:center;align-items:center;gap:8px}.error{padding:10px;border-radius:9px;background:#fee2e2;color:#991b1b;font-size:12px}.hint{text-align:center;color:#66736b}</style>
