<script lang="ts">
  import { Building2, CheckCircle2, ChevronLeft, ChevronRight, ImageUp, MapPin, PackagePlus, ShieldCheck } from "@lucide/svelte";
  import { cloudSaveOwnerBranding } from "../lib/tauri";
  let { onDone }: { onDone: () => void } = $props();
  let step=$state(0), saving=$state(false), message=$state("");
  let storeName=$state(""), legalName=$state(""), cnpj=$state(""), ie=$state(""), email=$state(""), phone=$state(""), address=$state(""), unitName=$state("Matriz"), logo=$state("");
  const steps=["Empresa","Primeira unidade","Identidade","Concluir"];
  async function chooseLogo(event:Event){const file=(event.currentTarget as HTMLInputElement).files?.[0];if(!file)return;const bitmap=await createImageBitmap(file);const scale=Math.min(1,512/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d")?.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();logo=canvas.toDataURL("image/webp",.84)}
  async function finish(){saving=true;message="";try{const saved=await cloudSaveOwnerBranding(storeName.trim(),logo);const branding={name:saved.display_name,logo:saved.logo_data_url||""};localStorage.setItem("commercectrl.client.branding",JSON.stringify(branding));localStorage.setItem("commercectrl.onboarding.profile",JSON.stringify({legalName,cnpj,ie,email,phone,address,unitName}));window.dispatchEvent(new CustomEvent("commercectrl-branding",{detail:branding}));message="Cadastro inicial salvo. Você pode completar os dados fiscais nas configurações quando iniciar a emissão.";step=3}catch(error){message=error instanceof Error?error.message:"Não foi possível salvar agora. Verifique a conexão."}finally{saving=false}}
</script>
<main class="onboarding"><aside><a href="/" class="wordmark">_,CTRL</a><div><p>Primeira abertura</p><h1>Vamos abrir sua operação.</h1><span>O cadastro fica por conta do administrador do mercado.</span></div><ol>{#each steps as label,index}<li class:current={step===index} class:done={step>index}><i>{#if step>index}<CheckCircle2 size={15}/>{:else}{index+1}{/if}</i>{label}</li>{/each}</ol><small>Você poderá revisar estes dados depois.</small></aside><section class="onboarding-content"><header><span>Etapa {step+1} de {steps.length}</span><strong>{steps[step]}</strong></header>
  {#if step===0}<div class="form"><div class="intro"><Building2/><h2>Quem é o mercado?</h2><p>Usamos esses dados para identificar a operação, documentos e comunicações do sistema.</p></div><label>Nome fantasia<input class="input" required bind:value={storeName} placeholder="Ex.: Mercadinho Martins"/></label><label>Razão social<input class="input" bind:value={legalName} placeholder="Nome empresarial"/></label><label>CNPJ<input class="input" bind:value={cnpj} inputmode="numeric" placeholder="00.000.000/0001-00"/></label><label>Inscrição estadual<input class="input" bind:value={ie} placeholder="Opcional por enquanto"/></label><label>E-mail do responsável<input class="input" type="email" bind:value={email} placeholder="dono@mercado.com.br"/></label><label>Telefone<input class="input" bind:value={phone} placeholder="(11) 99999-9999"/></label></div>
  {:else if step===1}<div class="form"><div class="intro"><MapPin/><h2>Cadastre a primeira unidade</h2><p>Preço, estoque, promoções e telas de TV podem ser administrados por unidade.</p></div><label>Nome da unidade<input class="input" bind:value={unitName}/></label><label class="span2">Endereço completo<input class="input" bind:value={address} placeholder="Rua, número, bairro, cidade e CEP"/></label><div class="callout span2"><ShieldCheck size={19}/><span>Os dados fiscais ficam separados por unidade. Eles podem ser concluídos antes da emissão de NFC-e.</span></div></div>
  {:else if step===2}<div class="form"><div class="intro"><ImageUp/><h2>Deixe o mercado reconhecível</h2><p>A logo aparece de forma elegante no cabeçalho, comprovante e TV de ofertas. Ela é convertida para WebP.</p></div><label class="span2 upload">Logo do mercado<input class="input" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onchange={chooseLogo}/></label>{#if logo}<div class="logo-box span2"><img src={logo} alt="Prévia da logo"/><span>Prévia pronta para sincronização.</span></div>{/if}<div class="callout span2"><PackagePlus size={19}/><span>O próximo passo dentro do sistema será importar ou cadastrar produtos e imagens reais.</span></div></div>
  {:else}<div class="complete"><CheckCircle2/><h2>Base da loja preparada.</h2><p>{message || "Revise os dados e confirme para salvar a identidade do tenant."}</p><button class="button" disabled={saving} onclick={onDone}>Ir para o painel</button></div>{/if}
  <footer>{#if step>0&&step<3}<button class="back" onclick={()=>step--}><ChevronLeft size={17}/>Voltar</button>{:else}<span></span>{/if}{#if step<2}<button class="next" disabled={step===0&&!storeName.trim()} onclick={()=>step++}>Continuar<ChevronRight size={17}/></button>{:else if step===2}<button class="next" disabled={saving} onclick={finish}>{saving?"Salvando…":"Salvar e concluir"}<ChevronRight size={17}/></button>{/if}</footer></section></main>
<style>
 .onboarding{min-height:100vh;display:grid;grid-template-columns:minmax(270px,34%) 1fr;background:#f5f4ef;color:#1a2924}.onboarding aside{padding:48px clamp(28px,5vw,80px);background:#153e31;color:#f4f2e8;display:flex;flex-direction:column}.wordmark{font:900 21px "Space Grotesk";letter-spacing:-.11em;color:#dced75;text-decoration:none}.onboarding aside>div{margin-top:clamp(65px,13vh,150px)}.onboarding aside p{color:#b6d1b3;font-size:13px}.onboarding h1{font:700 clamp(36px,4vw,58px)/.94 "Space Grotesk";letter-spacing:-.07em;margin:10px 0 14px}.onboarding aside span{color:#c6d8c3;line-height:1.5}.onboarding ol{padding:0;list-style:none;margin:75px 0 auto;display:grid;gap:20px}.onboarding li{display:flex;align-items:center;gap:12px;color:#99b5a7;font-weight:650}.onboarding li i{width:26px;height:26px;border:1px solid #57796a;border-radius:50%;display:grid;place-items:center;font-style:normal;font-size:12px}.onboarding li.current{color:white}.onboarding li.current i,.onboarding li.done i{background:#dced75;color:#153e31;border-color:#dced75}.onboarding aside small{color:#88a797}.onboarding-content{max-width:800px;width:100%;padding:clamp(32px,8vw,100px);margin:auto}.onboarding-content header{display:flex;justify-content:space-between;color:#668074;font-size:13px}.onboarding-content header strong{color:#153e31}.form{margin-top:72px;display:grid;grid-template-columns:1fr 1fr;gap:20px}.intro,.span2{grid-column:1/-1}.intro :global(svg),.complete :global(svg){width:35px;height:35px;color:#d94c2e}.intro h2,.complete h2{font:700 38px/.98 "Space Grotesk";letter-spacing:-.06em;margin:14px 0 10px}.intro p{max-width:540px;color:#617067;line-height:1.5}.form label{display:grid;gap:7px;font-size:12px;font-weight:750}.callout{display:flex;gap:10px;align-items:center;background:#e6ead8;padding:14px;color:#35543e;font-size:13px;line-height:1.4}.logo-box{display:flex;align-items:center;gap:16px}.logo-box img{width:120px;height:80px;object-fit:contain;background:white;border:1px solid #ccd4ca}.onboarding-content footer{margin-top:70px;display:flex;justify-content:space-between}.next,.back{display:flex;align-items:center;gap:5px;font:700 14px Inter;border:0;padding:12px 17px;cursor:pointer}.next{background:#153e31;color:white}.back{background:transparent;color:#27483a}.complete{margin-top:150px;max-width:530px}.complete :global(svg){width:50px;height:50px;color:#238456}.complete p{color:#617067;line-height:1.5;margin-bottom:25px}@media(max-width:700px){.onboarding{grid-template-columns:1fr}.onboarding aside{padding:28px}.onboarding aside>div{margin-top:40px}.onboarding ol{display:none}.onboarding aside small{display:none}.onboarding-content{padding:38px 24px}.form{margin-top:44px;grid-template-columns:1fr}.intro h2,.complete h2{font-size:32px}}
</style>
