<script lang="ts">
  import { onMount } from "svelte";
  import { Plus, Search, X, Pencil, Archive } from "@lucide/svelte";
  import { archiveProduct, listProducts, saveProduct } from "../lib/tauri";
  import { brl } from "../lib/format";
  import type { Product } from "../lib/types";
  let products = $state<Product[]>([]);
  let query = $state("");
  let open=$state(false), busy=$state(false), error=$state("");
  let editing=$state(false);
  let ean=$state(""), sku=$state(""), description=$state(""), brand=$state(""), price=$state(0), stock=$state(0), minimum=$state(10), imageUrl=$state("");
  onMount(async () => { products = await listProducts(); });
  let filtered = $derived(products.filter((p) => `${p.description} ${p.ean} ${p.part_number}`.toLowerCase().includes(query.toLowerCase())));
  function edit(item:Product){editing=true;ean=item.ean;sku=item.part_number;description=item.description;brand=item.brand??"";price=item.price_brl_cents/100;stock=item.stock_qty;minimum=item.min_stock;imageUrl=item.image_url??"";open=true}function reset(){open=false;editing=false;ean=sku=description=brand=imageUrl="";price=stock=0;minimum=10}
  async function imageFile(event:Event){const file=(event.currentTarget as HTMLInputElement).files?.[0];if(!file)return;const bitmap=await createImageBitmap(file);const scale=Math.min(1,700/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d")!.drawImage(bitmap,0,0,canvas.width,canvas.height);imageUrl=canvas.toDataURL("image/webp",.78);if(imageUrl.length>700000){error="Imagem ainda muito grande; escolha um arquivo menor.";imageUrl=""}}
  async function submit(){busy=true;error="";try{const item=await saveProduct({ean,part_number:sku,description,brand,price_brl_cents:Math.round(price*100),stock_qty:stock,min_stock:minimum,image_url:imageUrl||null});products=[item,...products.filter(p=>p.ean!==item.ean)];reset()}catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{busy=false}}
  async function archive(item:Product){if(!window.confirm(`Arquivar ${item.description}? O histórico de vendas será preservado.`))return;try{await archiveProduct(item.ean);products=products.filter((product)=>product.ean!==item.ean)}catch(cause){error=cause instanceof Error?cause.message:String(cause)}}
</script>

<article class="card">
  <div class="card-header"><div><h2>Catálogo de Produtos</h2><p class="small muted">Gerencie produtos, estoque e preços.</p></div><button class="button" onclick={()=>{editing=false;open=true}}><Plus size={17}/> Adicionar Produto</button></div>
  <div class="card-body toolbar"><div class="search"><Search size={17}/><input class="input" bind:value={query} placeholder="Buscar por nome ou código..." /></div><span class="spacer"></span><span class="small muted">{filtered.length} produtos</span></div>
  <div class="table-wrap"><table><thead><tr><th>Produto</th><th>Código</th><th>Status</th><th>Preço</th><th>Estoque</th><th>Ação</th></tr></thead><tbody>{#each filtered as product}<tr><td><strong>{product.description}</strong><br/><span class="small muted">{product.brand ?? "Sem marca"}</span></td><td>{product.ean}</td><td><span class:danger={product.stock_qty < product.min_stock} class:success={product.stock_qty >= product.min_stock} class="badge">{product.stock_qty < product.min_stock ? "Estoque baixo" : "Em estoque"}</span></td><td>{brl(product.price_brl_cents)}</td><td>{product.stock_qty}</td><td><div class="actions"><button class="icon-button" aria-label="Editar produto" onclick={()=>edit(product)}><Pencil size={16}/></button><button class="icon-button" aria-label="Arquivar produto" onclick={()=>archive(product)}><Archive size={16}/></button></div></td></tr>{/each}</tbody></table></div>
</article>
{#if open}<div class="modal-backdrop"><form class="modal card" onsubmit={(event)=>{event.preventDefault();submit()}}><div class="card-header"><h2>{editing?"Editar produto":"Novo produto"}</h2><button type="button" class="icon-button" onclick={reset}><X size={18}/></button></div><div class="card-body form-grid">{#if error}<span class="badge danger wide">{error}</span>{/if}<label>EAN<input class="input" required readonly={editing} bind:value={ean}/></label><label>SKU<input class="input" required bind:value={sku}/></label><label class="wide">Descrição<input class="input" required bind:value={description}/></label><label class="wide">Marca<input class="input" bind:value={brand}/></label><label>Preço (R$)<input class="input" required min="0" step="0.01" type="number" bind:value={price}/></label><label>Estoque atual<input class="input" required min="0" step="0.001" type="number" bind:value={stock}/></label><label>Estoque mínimo<input class="input" required min="0" step="0.001" type="number" bind:value={minimum}/></label><label class="wide">Imagem do produto (salva como WebP na nuvem)<input class="input" type="file" accept="image/png,image/jpeg,image/webp" onchange={imageFile}/></label>{#if imageUrl}<div class="wide image-preview"><img src={imageUrl} alt="Prévia"/><button type="button" class="button secondary" onclick={()=>imageUrl=""}>Remover imagem</button></div>{/if}</div><div class="card-footer modal-actions"><button type="button" class="button secondary" onclick={reset}>Cancelar</button><button class="button" disabled={busy}>{busy?"Salvando...":"Salvar"}</button></div></form></div>{/if}
<style>.search{position:relative;display:flex;align-items:center;max-width:430px;flex:1}.search :global(svg){position:absolute;left:12px;color:#737993}.search .input{padding-left:38px}.image-preview{display:flex;align-items:center;gap:12px}.image-preview img{width:90px;height:90px;object-fit:contain;border:1px solid var(--border);border-radius:10px;background:#fff}</style>
