<script lang="ts">
  import { onMount } from "svelte";
  import { Copy, Pencil, Plus, Tv, X } from "@lucide/svelte";
  import { getDisplaySettings, listPromotions, localDisplayLink, saveDisplaySettings, savePromotion, setPromotionActive, updatePromotion } from "../lib/tauri";
  import type { DisplaySettings, LocalDisplayLink, Promotion } from "../lib/types";
  let promotions=$state<Promotion[]>([]),open=$state(false),busy=$state(false),error=$state(""),display=$state<LocalDisplayLink|null>(null),copied=$state(false),settings=$state<DisplaySettings|null>(null),radiosText=$state(""),settingsMessage=$state("");
  let title=$state(""),subtitle=$state(""),priceLabel=$state(""),active=$state(true),editingId=$state<number|null>(null);
  onMount(async()=>{await load();try{settings=await getDisplaySettings();radiosText=settings.radios.map((radio)=>`${radio.name} | ${radio.url}`).join("\n")}catch(cause){settingsMessage=cause instanceof Error?cause.message:String(cause)}});
  async function load(){try{promotions=await listPromotions(true)}catch(cause){error=cause instanceof Error?cause.message:String(cause)}}
  function create(){editingId=null;title=subtitle=priceLabel="";active=true;error="";open=true}
  function edit(item:Promotion){editingId=item.id;title=item.title;subtitle=item.subtitle??"";priceLabel=item.price_label;active=item.active;error="";open=true}
  async function submit(){busy=true;error="";try{const saved=editingId===null?await savePromotion(title,subtitle,priceLabel,active):await updatePromotion(editingId,title,subtitle,priceLabel,active);promotions=editingId===null?[saved,...promotions]:promotions.map((item)=>item.id===saved.id?saved:item);open=false}catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{busy=false}}
  async function toggle(item:Promotion){try{await setPromotionActive(item.id,!item.active);item.active=!item.active;promotions=[...promotions]}catch(cause){error=cause instanceof Error?cause.message:String(cause)}}
  async function showDisplay(){try{display=await localDisplayLink();copied=false}catch(cause){error=cause instanceof Error?cause.message:String(cause)}}
  async function copyDisplay(){if(!display)return;try{await navigator.clipboard.writeText(display.url);copied=true}catch{error="Não foi possível copiar o link."}}
  async function saveTv(){if(!settings)return;busy=true;settingsMessage="";try{const radios=radiosText.split("\n").map((line)=>line.trim()).filter(Boolean).map((line)=>{const [name,...url]=line.split("|");return{name:name.trim(),url:url.join("|").trim()}});settings=await saveDisplaySettings({...settings,radios});settingsMessage="Modo TV atualizado nesta unidade."}catch(cause){settingsMessage=cause instanceof Error?cause.message:String(cause)}finally{busy=false}}
</script>
{#if error && !promotions.length}<div class="card card-body"><span class="badge danger">{error}</span></div>{:else}<article class="card"><div class="card-header"><div><h2>Promoções do Modo TV</h2><p class="small muted">Promoções desta unidade; a TV não recebe ofertas de outra filial.</p></div><div class="actions"><button class="button secondary" onclick={showDisplay}><Tv size={17}/> Link da TV</button><button class="button" onclick={create}><Plus size={17}/> Nova promoção</button></div></div>{#if display}<div class="card-body display-link"><strong>Modo TV desta unidade</strong><code>{display.url}</code><button class="button secondary" onclick={copyDisplay}><Copy size={15}/>{copied?"Copiado":"Copiar"}</button><small class="muted">{display.note}</small></div>{/if}{#if error}<div class="card-body"><span class="badge danger">{error}</span></div>{/if}<div class="table-wrap"><table><thead><tr><th>Título</th><th>Chamada</th><th>Preço</th><th>Status</th><th>Ação</th></tr></thead><tbody>{#each promotions as item}<tr><td><strong>{item.title}</strong></td><td>{item.subtitle??"—"}</td><td>{item.price_label}</td><td><span class:success={item.active} class:danger={!item.active} class="badge">{item.active?"Ativa":"Inativa"}</span></td><td><div class="actions"><button class="button secondary" onclick={()=>edit(item)}><Pencil size={15}/> Editar</button><button class="button secondary" onclick={()=>toggle(item)}>{item.active?"Desativar":"Ativar"}</button></div></td></tr>{/each}</tbody></table></div></article>{/if}
{#if open}<div class="modal-backdrop"><form class="modal card" onsubmit={(e)=>{e.preventDefault();submit()}}><div class="card-header"><h2>{editingId===null?"Nova promoção":"Editar promoção"}</h2><button type="button" class="icon-button" onclick={()=>open=false}><X size={18}/></button></div><div class="card-body form-grid">{#if error}<span class="badge danger wide">{error}</span>{/if}<label class="wide">Título<input class="input" required bind:value={title}/></label><label class="wide">Subtítulo<input class="input" bind:value={subtitle}/></label><label class="wide">Chamada de preço<input class="input" required placeholder="R$ 19,99 ou Leve 3, pague 2" bind:value={priceLabel}/></label><label class="wide">Publicação<select bind:value={active}><option value={true}>Ativa</option><option value={false}>Inativa</option></select></label></div><div class="card-footer modal-actions"><button type="button" class="button secondary" onclick={()=>open=false}>Cancelar</button><button class="button" disabled={busy}>{busy?"Salvando...":"Salvar"}</button></div></form></div>{/if}
{#if settings}<article class="card"><div class="card-header"><div><h2>Layout e mídia da TV</h2><p class="small muted">Configuração exclusiva desta unidade. A TV atualiza em até 5 segundos.</p></div></div><form class="card-body form-grid" onsubmit={(event)=>{event.preventDefault();saveTv()}}><label>Layout<select bind:value={settings.layout}><option value="promotions">Promoções em tela cheia</option><option value="video">Vídeo YouTube + promoções</option></select></label><label>Intervalo das promoções (segundos)<input class="input" type="number" min="5" max="120" bind:value={settings.promotion_interval_seconds}/></label>{#if settings.layout==="video"}<label class="wide">ID do vídeo YouTube<input class="input" placeholder="dQw4w9WgXcQ" bind:value={settings.youtube_id}/><small class="muted">Use somente o ID após <code>v=</code>, não a URL inteira.</small></label>{/if}<label class="wide">Rádios disponíveis<textarea class="input radio-list" rows="4" placeholder="Nome | https://stream.exemplo/radio" bind:value={radiosText}></textarea><small class="muted">Uma rádio por linha. Selecione abaixo a rádio que tocará na TV.</small></label><label class="wide">Rádio selecionada<select bind:value={settings.selected_radio_url}><option value={null}>Sem rádio</option>{#each radiosText.split("\n").map((line)=>line.split("|")).filter((parts)=>parts.length>1) as radio}<option value={radio.slice(1).join("|").trim()}>{radio[0].trim()}</option>{/each}</select></label>{#if settingsMessage}<p class="wide notice">{settingsMessage}</p>{/if}<div class="wide"><button class="button" disabled={busy}>{busy?"Salvando...":"Salvar configuração da TV"}</button></div></form></article>{/if}
