<script lang="ts">
  import { onMount } from "svelte";
  import { Download, Printer, Search } from "@lucide/svelte";
  import { cloudOwnerOverview, dashboardSummary, salesReport } from "../lib/tauri";
  import { brl } from "../lib/format";
  import type { DashboardSummary, OwnerOverview, SalesReportRow } from "../lib/types";
  const today=new Date().toISOString().slice(0,10);
  let summary=$state<DashboardSummary|null>(null),rows=$state<SalesReportRow[]>([]),error=$state(""),busy=$state(false);
  let owner=$state<OwnerOverview|null>(null),selectedUnitId=$state("");
  const selectedUnit=$derived(owner?.units.find((unit)=>unit.unit_id===selectedUnitId)??null);
  let from=$state(today),to=$state(today),payment=$state(""),terminal=$state(""),product=$state("");
  const total=$derived(rows.reduce((sum,row)=>sum+row.total_brl_cents,0));
  onMount(async()=>{try{summary=await dashboardSummary();await load()}catch(cause){error=cause instanceof Error?cause.message:String(cause)}});
  function bounds(){const start=Math.floor(new Date(`${from}T00:00:00`).getTime()/1000);const end=Math.floor(new Date(`${to}T00:00:00`).getTime()/1000)+86400;return[start,end] as const}
  async function load(){busy=true;error="";try{const[start,end]=bounds();rows=await salesReport(start,end,payment,terminal,product);owner=await cloudOwnerOverview(start,end).catch(()=>null)}catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{busy=false}}
  function csvCell(value:unknown){return `"${String(value??"").replaceAll('"','""')}"`}
  function exportCsv(){const header=["Venda","Data","Terminal","Pagamento","Itens","Total"];const lines=rows.map(row=>[row.uuid,new Date(row.created_at*1000).toLocaleString("pt-BR"),row.terminal_id,row.payment_method,row.items_count,(row.total_brl_cents/100).toFixed(2)].map(csvCell).join(";"));const blob=new Blob(["\uFEFF"+[header.map(csvCell).join(";"),...lines].join("\r\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`vendas-${from}-${to}.csv`;link.click();URL.revokeObjectURL(url)}
</script>
{#if error}<div class="card card-body"><span class="badge danger">{error}</span></div>{/if}
<div class="section-stack">
  {#if summary}<section class="grid grid-3"><article class="card card-body"><p class="small muted">Vendas filtradas</p><p class="metric">{brl(total)}</p></article><article class="card card-body"><p class="small muted">Operações</p><p class="metric">{rows.length}</p></article><article class="card card-body"><p class="small muted">Estoque crítico</p><p class="metric">{summary.low_stock_count}</p></article></section>{/if}
  <article class="card"><div class="card-header"><div><h2>Relatório de vendas</h2><p class="small muted">Consulta real do SQLite local, limitada a 5.000 registros.</p></div><div class="actions"><button class="button secondary" disabled={!rows.length} onclick={exportCsv}><Download size={16}/> CSV</button><button class="button secondary" disabled={!rows.length} onclick={()=>window.print()}><Printer size={16}/> Imprimir</button></div></div><form class="card-body filters" onsubmit={(event)=>{event.preventDefault();load()}}><label>De<input class="input" type="date" required bind:value={from}/></label><label>Até<input class="input" type="date" required bind:value={to}/></label><label>Pagamento<select bind:value={payment}><option value="">Todos</option><option value="cash">Dinheiro</option><option value="credit">Cartão</option><option value="pix">PIX</option></select></label><label>Terminal<input class="input" placeholder="Todos" bind:value={terminal}/></label><label>EAN do produto<input class="input" placeholder="Todos" bind:value={product}/></label><button class="button" disabled={busy}><Search size={16}/>{busy?"Consultando...":"Consultar"}</button></form><div class="table-wrap"><table><thead><tr><th>Data</th><th>Venda</th><th>Terminal</th><th>Pagamento</th><th>Itens</th><th>Total</th></tr></thead><tbody>{#each rows as row}<tr><td>{new Date(row.created_at*1000).toLocaleString("pt-BR")}</td><td><code>{row.uuid.slice(0,8)}</code></td><td>{row.terminal_id}</td><td><span class="badge">{row.payment_method}</span></td><td>{row.items_count}</td><td><strong>{brl(row.total_brl_cents)}</strong></td></tr>{:else}<tr><td colspan="6" class="muted">Nenhuma venda no período selecionado.</td></tr>{/each}</tbody></table></div></article>
  {#if owner}<article class="card"><div class="card-header"><div><h2>Painel do proprietário · todas as unidades</h2><p class="small muted">Consolidado no backend. Selecione uma loja para analisar sua operação sem misturar estoque, preço ou venda das demais.</p></div><div class="owner-total"><span>{owner.sales_count} vendas</span><strong>{brl(owner.total_brl_cents)}</strong></div></div><div class="unit-tabs" aria-label="Filtrar unidade"><button class:active={!selectedUnitId} onclick={()=>selectedUnitId=""}>Todas <span>{owner.units.length}</span></button>{#each owner.units as unit}<button class:active={selectedUnitId===unit.unit_id} onclick={()=>selectedUnitId=unit.unit_id}>{unit.unit_name}<small>{unit.unit_code}</small></button>{/each}</div>{#if selectedUnit}<div class="unit-focus"><div><span>Unidade selecionada</span><strong>{selectedUnit.unit_name}</strong></div><div><span>Faturamento</span><strong>{brl(selectedUnit.total_brl_cents)}</strong></div><div><span>Estoque crítico</span><strong class:danger={selectedUnit.low_stock_skus>0}>{selectedUnit.low_stock_skus} SKUs</strong></div></div>{/if}<div class="table-wrap"><table><thead><tr><th>Unidade</th><th>Vendas</th><th>Itens</th><th>Estoque</th><th>Crítico</th><th>Total</th></tr></thead><tbody>{#each owner.units.filter((unit)=>!selectedUnitId||unit.unit_id===selectedUnitId) as unit}<tr><td><strong>{unit.unit_name}</strong><br/><small class="muted">{unit.unit_code}</small></td><td>{unit.sales_count}</td><td>{unit.items_count}</td><td>{unit.stock_skus} SKUs</td><td><span class:danger={unit.low_stock_skus>0} class="badge">{unit.low_stock_skus}</span></td><td><strong>{brl(unit.total_brl_cents)}</strong></td></tr>{/each}</tbody></table></div></article>
  <article class="card"><div class="card-header"><div><h2>Produtos que mais vendem</h2><p class="small muted">Ranking por faturamento no período selecionado, em todas as unidades.</p></div></div><div class="table-wrap"><table><thead><tr><th>Produto</th><th>EAN</th><th>Quantidade</th><th>Unidades</th><th>Faturamento</th></tr></thead><tbody>{#each owner.top_products as item}<tr><td><strong>{item.description}</strong></td><td><code>{item.ean}</code></td><td>{item.qty_sold.toLocaleString("pt-BR")}</td><td>{item.units_sold_in}</td><td><strong>{brl(item.revenue_brl_cents)}</strong></td></tr>{:else}<tr><td colspan="5" class="muted">Nenhuma venda sincronizada no período.</td></tr>{/each}</tbody></table></div></article>{/if}
</div>
<style>.filters{display:grid;grid-template-columns:repeat(5,minmax(120px,1fr)) auto;gap:10px;align-items:end}.filters label{display:grid;gap:5px;font-size:11px;color:var(--muted);font-weight:700}.actions,.owner-total{display:flex;gap:8px;align-items:center}.owner-total{flex-direction:column;align-items:end}.owner-total span{font-size:12px;color:var(--muted)}.unit-tabs{display:flex;gap:8px;overflow:auto;padding:0 18px 16px}.unit-tabs button{border:1px solid var(--border);background:var(--surface-2);color:var(--text);border-radius:10px;padding:8px 10px;display:grid;gap:2px;text-align:left;white-space:nowrap;font-weight:700;cursor:pointer}.unit-tabs button small{font-size:10px;color:var(--muted)}.unit-tabs button span{font-size:11px;display:inline}.unit-tabs button.active{background:var(--primary);border-color:var(--primary);color:#fff}.unit-tabs button.active small{color:#e8fff0}.unit-focus{margin:0 18px 18px;padding:14px;border:1px solid var(--border);border-radius:12px;display:grid;grid-template-columns:repeat(3,1fr);gap:12px;background:var(--surface-2)}.unit-focus div{display:grid;gap:4px}.unit-focus span{font-size:11px;color:var(--muted)}.unit-focus strong{font-size:16px}@media(max-width:1100px){.filters{grid-template-columns:repeat(2,1fr)}}@media(max-width:640px){.unit-focus{grid-template-columns:1fr}.owner-total{align-items:start}.card-header{align-items:flex-start;flex-direction:column}}@media print{.filters,.actions,:global(.sidebar),:global(.topbar),.unit-tabs{display:none!important}}</style>
