<script lang="ts">
  import { onMount } from "svelte"; import { Sparkles, X } from "@lucide/svelte"; import { createPurchaseOrder, listProducts } from "../lib/tauri"; import type { Product } from "../lib/types";
  let products=$state<Product[]>([]), selected=$state<Product|null>(null), error=$state(""), message=$state(""), busy=$state(false);
  onMount(async()=>{try{products=(await listProducts()).sort((a,b)=>(a.min_stock?a.stock_qty/a.min_stock:999)-(b.min_stock?b.stock_qty/b.min_stock:999))}catch(cause){error=cause instanceof Error?cause.message:"Falha ao carregar estoque"}});
  const suggested=(product:Product)=>Math.max(1,Math.ceil(product.min_stock*2-product.stock_qty));
  async function create(){if(!selected)return;busy=true;try{const id=await createPurchaseOrder(selected.ean,suggested(selected));message=`Pedido #${id} criado e aguardando sincronização`;selected=null}catch(cause){error=String(cause)}finally{busy=false}}
</script>
{#if error}<div class="card card-body"><span class="badge danger">{error}</span></div>{:else}<article class="card"><div class="card-header"><div><h2>Reposição Inteligente de Estoque</h2><p class="small muted">Calculada a partir do estoque mínimo persistido.</p>{#if message}<span class="badge success">{message}</span>{/if}</div></div><div class="table-wrap"><table><thead><tr><th>Produto</th><th>Status</th><th>Atual / mínimo</th><th>Ação</th></tr></thead><tbody>{#each products as product}<tr><td><strong>{product.description}</strong></td><td><span class:danger={product.stock_qty<product.min_stock} class:warning={product.stock_qty>=product.min_stock&&product.stock_qty<product.min_stock*1.5} class:success={product.stock_qty>=product.min_stock*1.5} class="badge">{product.stock_qty<product.min_stock?"Crítico":product.stock_qty<product.min_stock*1.5?"Baixo":"OK"}</span></td><td><div class="stock"><span style={`width:${product.min_stock?Math.min(100,product.stock_qty/product.min_stock*100):100}%`}></span></div><small>{product.stock_qty} / {product.min_stock}</small></td><td><button class="button secondary" onclick={()=>selected=product}><Sparkles size={15}/> Sugerir reposição</button></td></tr>{/each}</tbody></table></div></article>{/if}
{#if selected}<div class="modal-backdrop"><section class="card modal"><div class="card-header"><div><h2>Sugestão de Reposição</h2><p class="small muted">{selected.description}</p></div><button class="icon-button" onclick={()=>selected=null}><X size={18}/></button></div><div class="card-body suggestion"><span class="stat-icon"><Sparkles size={20}/></span><p class="metric">{suggested(selected)} unidades</p><p class="muted">Quantidade para alcançar duas vezes o estoque mínimo cadastrado. Confirmação humana obrigatória.</p></div><div class="card-footer modal-actions"><button class="button secondary" onclick={()=>selected=null}>Fechar</button><button class="button" disabled={busy} onclick={create}>{busy?"Criando...":"Criar pedido de compra"}</button></div></section></div>{/if}
<style>.stock{width:120px;height:6px;background:#eceef5;border-radius:99px;overflow:hidden;display:inline-block;margin-right:8px}.stock span{display:block;height:100%;background:linear-gradient(90deg,#dc3e4d,#4e59b5)}.suggestion{text-align:center;display:grid;justify-items:center;gap:10px}.suggestion p.muted{max-width:400px;line-height:1.6}</style>
