<script lang="ts">
  import { CheckCircle2, Circle, Database, ExternalLink, GitBranch, ServerCog, ShieldCheck } from "@lucide/svelte";
  let { onBack }: { onBack: () => void } = $props();
  const steps = [
    {title:"Supabase",icon:Database,url:"https://supabase.com/dashboard/project/sqwpkwsjbbkylbdpjrlu",items:["Mantenha RLS ativo nas tabelas de negócio.","Valide os buckets product-images e desktop-releases.","Use no Render a URL do Connection Pooler, porta 6543 — não a URL direta do banco."]},
    {title:"Render",icon:ServerCog,url:"https://dashboard.render.com/",items:["Defina DATABASE_URL pelo Connection Pooler.","Configure PORT, SUPERADMIN_EMAIL e SUPERADMIN_PASSWORD.","Faça redeploy e confirme /health antes de liberar terminais."]},
    {title:"GitHub",icon:GitBranch,url:"https://github.com/leocalazans/adega_pro/settings/secrets/actions",items:["Desbloqueie Actions caso haja pendência na conta.","Cadastre as chaves do updater e as variáveis de produção como Secrets.","Rode Release Windows signed updater para publicar a primeira versão assinada."]},
  ];
</script>

<main class="setup"><header><a href="/" class="mark">_,CTRL</a><button onclick={onBack}>Voltar</button></header><section class="hero"><div><p>CHECKLIST DO ADMINISTRADOR</p><h1>Deixe a operação pronta para vender.</h1><span>Este roteiro não armazena senhas: ele mostra a ordem segura para configurar banco, backend e atualizações.</span></div><aside><small>O que já existe</small><strong>Backend Rust, PDV local e canal de atualização.</strong><em>A primeira release assinada libera o update automático.</em></aside></section><section class="steps">{#each steps as step,index}<article><div class="number">0{index+1}<svelte:component this={step.icon} size={21}/></div><div><h2>{step.title}</h2><ul>{#each step.items as item}<li><Circle size={11}/>{item}</li>{/each}</ul></div><a href={step.url} target="_blank" rel="noreferrer">Abrir {step.title}<ExternalLink size={14}/></a></article>{/each}</section><section class="notice"><ShieldCheck size={24}/><div><h2>Antes de liberar o download</h2><p>Teste login, licença e sincronização num terminal de homologação. Nunca coloque a Service Role do Supabase em variáveis públicas do frontend.</p></div></section><footer><CheckCircle2 size={14}/>CommerceCTRL · roteiro de implantação local e cloud</footer></main>

<style>
.setup{--ink:#193128;--forest:#17553a;--paper:#f4f0e5;min-height:100vh;background:var(--paper);color:var(--ink);font-family:Inter,system-ui,sans-serif;padding:0 clamp(22px,7vw,110px) 50px}.setup header{height:76px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #cdd2bc}.mark{font:900 23px "Space Grotesk";letter-spacing:-.12em;color:var(--forest);text-decoration:none}.setup button{border:0;background:transparent;color:var(--forest);font-weight:800;cursor:pointer}.hero{max-width:1120px;margin:auto;padding:clamp(58px,10vw,130px) 0;display:grid;grid-template-columns:1.1fr .72fr;align-items:end;gap:80px}.hero p{font-size:12px;font-weight:800;color:#4c765b}.hero h1{margin:12px 0 24px;font:700 clamp(46px,6vw,78px)/.91 "Space Grotesk";letter-spacing:-.08em}.hero span{max-width:620px;display:block;color:#52655a;font-size:18px;line-height:1.5}.hero aside{border-left:4px solid #d7e96d;background:var(--forest);color:#f7f5ee;padding:26px;box-shadow:12px 12px 0 #d7e96d;display:grid;gap:8px}.hero aside small{color:#c9dfcb}.hero aside strong{font:700 27px/1.02 "Space Grotesk";letter-spacing:-.05em}.hero aside em{font-style:normal;font-size:13px;line-height:1.5;color:#d6e2d7}.steps{max-width:1120px;margin:auto;border-top:1px solid #cdd2bc}.steps article{display:grid;grid-template-columns:100px 1fr auto;gap:24px;padding:31px 0;border-bottom:1px solid #cdd2bc}.number{display:flex;gap:11px;align-items:center;color:#e34d2e;font:700 25px "Space Grotesk"}.steps h2{font:700 32px "Space Grotesk";letter-spacing:-.05em;margin:0}.steps ul{display:grid;gap:10px;padding:0;list-style:none;margin:17px 0 0;color:#4e6155;font-size:14px;line-height:1.5}.steps li{display:flex;gap:12px}.steps li :global(svg){margin-top:5px;flex:none;color:#69a76f}.steps a{height:max-content;display:flex;align-items:center;gap:7px;text-decoration:none;color:#1a563a;border:1px solid #52725c;padding:10px 13px;font-weight:800;font-size:13px}.notice{max-width:1120px;margin:38px auto 0;padding:23px;display:flex;gap:14px;border:1px solid #b5c5ad;background:white}.notice :global(svg),footer :global(svg){color:#1d8a55;flex:none}.notice h2{font:700 23px "Space Grotesk";letter-spacing:-.04em;margin:0}.notice p{font-size:14px;line-height:1.5;color:#53665a;margin:8px 0 0}footer{max-width:1120px;margin:29px auto 0;display:flex;gap:7px;align-items:center;font-size:12px;color:#66776a}@media(max-width:760px){.hero{grid-template-columns:1fr;gap:45px}.steps article{grid-template-columns:1fr;gap:15px}.steps a{width:max-content}.hero aside{max-width:480px}}
</style>
